# Generated by Django 3.2.6 on 2021-08-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='user',
        ),
    ]
